/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialInfoRouteImport } from './routes/social-info'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstallmentsRouteImport } from './routes/installments'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PartnerRouteImport } from './routes/_partner'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as CheckoutRouteRouteImport } from './routes/checkout/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as PaymentCallbackRouteImport } from './routes/payment/callback'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout/payment'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthPartnerRegisterRouteImport } from './routes/auth/partner-register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTorobRouteImport } from './routes/admin/torob'
import { Route as AdminTokensRouteImport } from './routes/admin/tokens'
import { Route as AdminStorageRouteImport } from './routes/admin/storage'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminInstallmentsRouteImport } from './routes/admin/installments'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminAiDiagnosticsRouteImport } from './routes/admin/ai-diagnostics'
import { Route as AdminAiConfigRouteImport } from './routes/admin/ai-config'
import { Route as PartnerPartnerPurchasesRouteImport } from './routes/_partner/partner/purchases'
import { Route as PartnerPartnerProductsRouteImport } from './routes/_partner/partner/products'
import { Route as PartnerPartnerDashboardRouteImport } from './routes/_partner/partner/dashboard'

const SocialInfoRoute = SocialInfoRouteImport.update({
  id: '/social-info',
  path: '/social-info',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentsRoute = InstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/_partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPartnerRegisterRoute = AuthPartnerRegisterRouteImport.update({
  id: '/partner-register',
  path: '/partner-register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTorobRoute = AdminTorobRouteImport.update({
  id: '/torob',
  path: '/torob',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInstallmentsRoute = AdminInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAiDiagnosticsRoute = AdminAiDiagnosticsRouteImport.update({
  id: '/ai-diagnostics',
  path: '/ai-diagnostics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAiConfigRoute = AdminAiConfigRouteImport.update({
  id: '/ai-config',
  path: '/ai-config',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PartnerPartnerPurchasesRoute = PartnerPartnerPurchasesRouteImport.update({
  id: '/partner/purchases',
  path: '/partner/purchases',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerPartnerProductsRoute = PartnerPartnerProductsRouteImport.update({
  id: '/partner/products',
  path: '/partner/products',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerPartnerDashboardRoute = PartnerPartnerDashboardRouteImport.update({
  id: '/partner/dashboard',
  path: '/partner/dashboard',
  getParentRoute: () => PartnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/checkout': typeof CheckoutRouteRouteWithChildren
  '/profile': typeof ProfileRouteRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/cart': typeof CartRoute
  '/installments': typeof InstallmentsRoute
  '/login': typeof LoginRoute
  '/social-info': typeof SocialInfoRoute
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/torob': typeof AdminTorobRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/partner-register': typeof AuthPartnerRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/partner/dashboard': typeof PartnerPartnerDashboardRoute
  '/partner/products': typeof PartnerPartnerProductsRoute
  '/partner/purchases': typeof PartnerPartnerPurchasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/profile': typeof ProfileRouteRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/cart': typeof CartRoute
  '/installments': typeof InstallmentsRoute
  '/login': typeof LoginRoute
  '/social-info': typeof SocialInfoRoute
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/torob': typeof AdminTorobRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/partner-register': typeof AuthPartnerRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/products': typeof ProductsIndexRoute
  '/partner/dashboard': typeof PartnerPartnerDashboardRoute
  '/partner/products': typeof PartnerPartnerProductsRoute
  '/partner/purchases': typeof PartnerPartnerPurchasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/checkout': typeof CheckoutRouteRouteWithChildren
  '/profile': typeof ProfileRouteRoute
  '/_partner': typeof PartnerRouteWithChildren
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/cart': typeof CartRoute
  '/installments': typeof InstallmentsRoute
  '/login': typeof LoginRoute
  '/social-info': typeof SocialInfoRoute
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/torob': typeof AdminTorobRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/partner-register': typeof AuthPartnerRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/_partner/partner/dashboard': typeof PartnerPartnerDashboardRoute
  '/_partner/partner/products': typeof PartnerPartnerProductsRoute
  '/_partner/partner/purchases': typeof PartnerPartnerPurchasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/profile'
    | '/about'
    | '/about-us'
    | '/cart'
    | '/installments'
    | '/login'
    | '/social-info'
    | '/admin/ai-config'
    | '/admin/ai-diagnostics'
    | '/admin/content'
    | '/admin/installments'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/storage'
    | '/admin/tokens'
    | '/admin/torob'
    | '/admin/users'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/partner-register'
    | '/blog/$slug'
    | '/checkout/payment'
    | '/payment/callback'
    | '/products/$slug'
    | '/admin/'
    | '/blog/'
    | '/checkout/'
    | '/products/'
    | '/partner/dashboard'
    | '/partner/products'
    | '/partner/purchases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/about'
    | '/about-us'
    | '/cart'
    | '/installments'
    | '/login'
    | '/social-info'
    | '/admin/ai-config'
    | '/admin/ai-diagnostics'
    | '/admin/content'
    | '/admin/installments'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/storage'
    | '/admin/tokens'
    | '/admin/torob'
    | '/admin/users'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/partner-register'
    | '/blog/$slug'
    | '/checkout/payment'
    | '/payment/callback'
    | '/products/$slug'
    | '/admin'
    | '/blog'
    | '/checkout'
    | '/products'
    | '/partner/dashboard'
    | '/partner/products'
    | '/partner/purchases'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/profile'
    | '/_partner'
    | '/about'
    | '/about-us'
    | '/cart'
    | '/installments'
    | '/login'
    | '/social-info'
    | '/admin/ai-config'
    | '/admin/ai-diagnostics'
    | '/admin/content'
    | '/admin/installments'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/storage'
    | '/admin/tokens'
    | '/admin/torob'
    | '/admin/users'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/partner-register'
    | '/blog/$slug'
    | '/checkout/payment'
    | '/payment/callback'
    | '/products/$slug'
    | '/admin/'
    | '/blog/'
    | '/checkout/'
    | '/products/'
    | '/_partner/partner/dashboard'
    | '/_partner/partner/products'
    | '/_partner/partner/purchases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CheckoutRouteRoute: typeof CheckoutRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  AboutRoute: typeof AboutRoute
  AboutUsRoute: typeof AboutUsRoute
  CartRoute: typeof CartRoute
  InstallmentsRoute: typeof InstallmentsRoute
  LoginRoute: typeof LoginRoute
  SocialInfoRoute: typeof SocialInfoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social-info': {
      id: '/social-info'
      path: '/social-info'
      fullPath: '/social-info'
      preLoaderRoute: typeof SocialInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installments': {
      id: '/installments'
      path: '/installments'
      fullPath: '/installments'
      preLoaderRoute: typeof InstallmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_partner': {
      id: '/_partner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/partner-register': {
      id: '/auth/partner-register'
      path: '/partner-register'
      fullPath: '/auth/partner-register'
      preLoaderRoute: typeof AuthPartnerRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/torob': {
      id: '/admin/torob'
      path: '/torob'
      fullPath: '/admin/torob'
      preLoaderRoute: typeof AdminTorobRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tokens': {
      id: '/admin/tokens'
      path: '/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/installments': {
      id: '/admin/installments'
      path: '/installments'
      fullPath: '/admin/installments'
      preLoaderRoute: typeof AdminInstallmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ai-diagnostics': {
      id: '/admin/ai-diagnostics'
      path: '/ai-diagnostics'
      fullPath: '/admin/ai-diagnostics'
      preLoaderRoute: typeof AdminAiDiagnosticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ai-config': {
      id: '/admin/ai-config'
      path: '/ai-config'
      fullPath: '/admin/ai-config'
      preLoaderRoute: typeof AdminAiConfigRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_partner/partner/purchases': {
      id: '/_partner/partner/purchases'
      path: '/partner/purchases'
      fullPath: '/partner/purchases'
      preLoaderRoute: typeof PartnerPartnerPurchasesRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/_partner/partner/products': {
      id: '/_partner/partner/products'
      path: '/partner/products'
      fullPath: '/partner/products'
      preLoaderRoute: typeof PartnerPartnerProductsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/_partner/partner/dashboard': {
      id: '/_partner/partner/dashboard'
      path: '/partner/dashboard'
      fullPath: '/partner/dashboard'
      preLoaderRoute: typeof PartnerPartnerDashboardRouteImport
      parentRoute: typeof PartnerRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAiConfigRoute: typeof AdminAiConfigRoute
  AdminAiDiagnosticsRoute: typeof AdminAiDiagnosticsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminInstallmentsRoute: typeof AdminInstallmentsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminTokensRoute: typeof AdminTokensRoute
  AdminTorobRoute: typeof AdminTorobRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAiConfigRoute: AdminAiConfigRoute,
  AdminAiDiagnosticsRoute: AdminAiDiagnosticsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminInstallmentsRoute: AdminInstallmentsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminTokensRoute: AdminTokensRoute,
  AdminTorobRoute: AdminTorobRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPartnerRegisterRoute: typeof AuthPartnerRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPartnerRegisterRoute: AuthPartnerRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CheckoutRouteRouteChildren {
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteRouteChildren: CheckoutRouteRouteChildren = {
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteRouteWithChildren = CheckoutRouteRoute._addFileChildren(
  CheckoutRouteRouteChildren,
)

interface PartnerRouteChildren {
  PartnerPartnerDashboardRoute: typeof PartnerPartnerDashboardRoute
  PartnerPartnerProductsRoute: typeof PartnerPartnerProductsRoute
  PartnerPartnerPurchasesRoute: typeof PartnerPartnerPurchasesRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerPartnerDashboardRoute: PartnerPartnerDashboardRoute,
  PartnerPartnerProductsRoute: PartnerPartnerProductsRoute,
  PartnerPartnerPurchasesRoute: PartnerPartnerPurchasesRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CheckoutRouteRoute: CheckoutRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRoute,
  PartnerRoute: PartnerRouteWithChildren,
  AboutRoute: AboutRoute,
  AboutUsRoute: AboutUsRoute,
  CartRoute: CartRoute,
  InstallmentsRoute: InstallmentsRoute,
  LoginRoute: LoginRoute,
  SocialInfoRoute: SocialInfoRoute,
  BlogSlugRoute: BlogSlugRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
