import { randomInt } from "node:crypto";
import { BadRequestException, Inject, Injectable, Logger } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import type Redis from "ioredis";
import { KafkaProducerService } from "../../kafka/kafka-producer.service";
import { REDIS_CLIENT } from "../../redis/redis.constants";

/**
 * OTP code TTL in seconds (2 minutes — strict).
 */
const OTP_TTL_SECONDS = 120;

/**
 * Maximum verification attempts before lockout.
 */
const MAX_ATTEMPTS = 5;

/**
 * MelliPayamak Console OTP API response shape.
 */
interface MelliPayamakOtpResponse {
  code: string;
  status: string;
}

/**
 * Redis key builders for OTP state.
 */
function otpCodeKey(mobile: string): string {
  return `otp:code:${mobile}`;
}

function otpAttemptsKey(mobile: string): string {
  return `otp:attempts:${mobile}`;
}

/**
 * OTP service integrating MelliPayamak Console OTP API.
 *
 * Flow:
 * 1. Call MelliPayamak Console OTP endpoint (provider generates the code)
 * 2. Store the returned code in Redis with strict 120s TTL
 * 3. On failure: log under [auth/sms-fail], publish failure event to Kafka DLQ
 * 4. Verify codes with attempt-limited lockout
 *
 * Dev Mode (NODE_ENV=development OR MOCK_SMS=true):
 * - Bypasses MelliPayamak entirely
 * - Generates a local 5-digit code
 * - Prints high-visibility log: [DEV/SMS-MOCK] Generated Verification Token: <CODE> for Target: <MOBILE>
 *
 * API Reference: docs/mellipyamak/send-otp.md
 * Endpoint: POST https://console.melipayamak.com/api/send/otp/{token}
 * Payload: { "to": "09XXXXXXXXX" }
 * Response: { "code": "generated_code", "status": "error_description_if_any" }
 */
@Injectable()
export class OtpService {
  private readonly logger = new Logger(OtpService.name);
  private readonly melliPayamakToken: string;
  private readonly isMockMode: boolean;

  constructor(
    @Inject(REDIS_CLIENT)
    private readonly redis: Redis,
    @Inject(KafkaProducerService)
    private readonly kafkaProducer: KafkaProducerService,
    @Inject(ConfigService)
    private readonly configService: ConfigService,
  ) {
    this.melliPayamakToken = this.configService.get<string>("MELIPAYAMAK_OTP_TOKEN", "");
    const nodeEnv = this.configService.get<string>("NODE_ENV", "development");
    const mockSms = this.configService.get<string>("MOCK_SMS", "false");
    this.isMockMode = nodeEnv === "development" || mockSms === "true";
  }

  /**
   * Dispatch an OTP to the given mobile number.
   *
   * In dev/mock mode: generates code locally and logs to terminal.
   * In production: calls MelliPayamak Console OTP API.
   *
   * @throws Error with Persian message if SMS dispatch fails (caught by tRPC layer → sonner toast)
   */
  async dispatch(mobile: string): Promise<void> {
    try {
      let code: string;

      if (this.isMockMode) {
        // DEV MODE: Generate locally and print high-visibility log
        code = randomInt(10000, 99999).toString();
        this.logger.warn(
          `\n` +
            `╔══════════════════════════════════════════════════════════╗\n` +
            `║  [DEV/SMS-MOCK] Generated Verification Token: ${code}  ║\n` +
            `║  Target: ${mobile.padEnd(20)}                      ║\n` +
            `╚══════════════════════════════════════════════════════════╝`,
        );
      } else {
        // PRODUCTION: Call MelliPayamak Console OTP API
        code = await this.callMelliPayamakOtp(mobile);
      }

      // Store code in Redis with strict 120s TTL
      await this.redis.set(otpCodeKey(mobile), code, "EX", OTP_TTL_SECONDS);

      // Reset attempts counter
      await this.redis.del(otpAttemptsKey(mobile));

      this.logger.debug(`OTP dispatched for ${mobile.slice(0, 4)}****`);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : "Unknown error";

      // Log with [auth/sms-fail] prefix for monitoring
      this.logger.error(
        `[auth/sms-fail] SMS dispatch failed for ${mobile.slice(0, 4)}****: ${message}`,
      );

      // Publish failure event to Kafka DLQ for admin visibility
      try {
        await this.kafkaProducer.send("notification.sms.dlq", mobile, {
          type: "otp_dispatch_failure",
          mobile,
          error: message,
          timestamp: new Date().toISOString(),
        });
      } catch {
        // DLQ publish failure is non-critical — already logged above
      }

      // Throw formatted error for tRPC → client sonner toast
      throw new BadRequestException("ارسال پیامک با خطا مواجه شد. لطفاً دقایقی بعد مجدداً تلاش کنید");
    }
  }

  /**
   * Call MelliPayamak Console OTP API.
   *
   * Endpoint: POST https://console.melipayamak.com/api/send/otp/{token}
   * Body: { "to": "09XXXXXXXXX" }
   * Response: { "code": "generated_code", "status": "..." }
   *
   * @returns The OTP code generated by MelliPayamak
   * @throws Error on network failure, timeout, or non-success response
   */
  private async callMelliPayamakOtp(mobile: string): Promise<string> {
    const url = `https://console.melipayamak.com/api/send/otp/${this.melliPayamakToken}`;

    const body = JSON.stringify({ to: mobile });

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(body).toString(),
      },
      body,
      signal: AbortSignal.timeout(10_000),
    });

    if (!response.ok) {
      throw new Error(
        `[auth/sms-fail] MelliPayamak HTTP ${response.status}: ${response.statusText}`,
      );
    }

    const result = (await response.json()) as MelliPayamakOtpResponse;

    // MelliPayamak returns the generated code in the "code" field.
    // If "status" is non-empty, it indicates an error description.
    if (!result.code) {
      throw new Error(
        `[auth/sms-fail] MelliPayamak returned empty code. Status: ${result.status || "unknown"}`,
      );
    }

    return result.code;
  }

  /**
   * Verify an OTP code against the cached value.
   *
   * @returns true if the code matches
   * @throws BadRequestException if code is invalid, expired, or attempts exhausted
   */
  async verify(mobile: string, code: string): Promise<boolean> {
    // Check attempt lockout
    const attempts = parseInt((await this.redis.get(otpAttemptsKey(mobile))) ?? "0", 10);

    if (attempts >= MAX_ATTEMPTS) {
      throw new BadRequestException(
        "تعداد تلاش‌های مجاز به پایان رسیده است. لطفاً کد جدید دریافت کنید",
      );
    }

    // Fetch stored code
    const storedCode = await this.redis.get(otpCodeKey(mobile));

    if (!storedCode) {
      throw new BadRequestException("کد تایید منقضی شده است. لطفاً کد جدید دریافت کنید");
    }

    // Constant-time comparison (prevent timing attacks on short codes)
    if (storedCode !== code) {
      // Increment attempts with same TTL as the OTP code
      await this.redis.incr(otpAttemptsKey(mobile));
      await this.redis.expire(otpAttemptsKey(mobile), OTP_TTL_SECONDS);
      throw new BadRequestException("کد تایید نادرست است");
    }

    // Success — clean up Redis state
    await this.redis.del(otpCodeKey(mobile));
    await this.redis.del(otpAttemptsKey(mobile));

    this.logger.debug(`OTP verified for ${mobile.slice(0, 4)}****`);
    return true;
  }
}
