import { json, pgEnum, pgTable, text, timestamp, uuid, varchar, vector } from "drizzle-orm/pg-core";
import { users } from "./users.js";

/**
 * Enum for message sender identification.
 */
export const aiMessageSenderEnum = pgEnum("ai_message_sender", ["user", "assistant"]);

/**
 * Enum for message input modality type.
 */
export const aiMessageTypeEnum = pgEnum("ai_message_type", ["text", "audio_transcript"]);

/**
 * Persistent AI chat sessions supporting both authenticated users and guests.
 *
 * - Authenticated users: user_id is set, guest_session_id may be null
 * - Guest sessions: user_id is null, guest_session_id tracks the visitor
 * - On merge: user_id is atomically set, guest key deleted from Redis
 */
export const aiChatSessions = pgTable("ai_chat_sessions", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** Authenticated user FK — null for guest sessions */
  userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }),

  /** Guest session tracking token (UUID from client cookie/localStorage) */
  guestSessionId: varchar("guest_session_id", { length: 128 }),

  /** Dynamic session title — auto-generated by Kafka telemetry consumer */
  title: text("title"),

  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

/**
 * Individual messages within an AI chat session.
 *
 * Stores both user inputs and assistant responses with metadata
 * for marketing pipeline extraction and analytics.
 */
export const aiChatMessages = pgTable("ai_chat_messages", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** Parent chat session FK */
  sessionId: uuid("session_id")
    .notNull()
    .references(() => aiChatSessions.id, { onDelete: "cascade" }),

  /** Who sent this message */
  sender: aiMessageSenderEnum("sender").notNull(),

  /** Input modality: direct text or transcribed audio */
  messageType: aiMessageTypeEnum("message_type").notNull().default("text"),

  /** The actual text content (user query or assistant response) */
  content: text("content").notNull(),

  /** 1536-dimensional embedding vector representing the message query */
  embedding: vector("embedding", { dimensions: 1536 }),

  /**
   * Structured metadata for marketing and analytics pipelines.
   * May contain: matched product IDs, user intent tags, browser info,
   * similarity scores, or any extracted customer interest signals.
   */
  metadata: json("metadata").$type<{
    matchedProductIds?: string[];
    intentTags?: string[];
    browserInfo?: string;
    similarityScore?: number;
  }>(),

  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});
